name: Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Print Path
        run: xcode-select -print-path

      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Install Bundler
        run: gem install bundler
        
      - name: Install gems
        run: bundle install

      - name: Test - Fastlane tests
        run: bundle exec fastlane tests


